### ISSUE TITLE
Call to undefined method Symfony\Component\Translation\Translator::getMessages()

### ISSUE THREAD

**Issue by jsphpl** [jenssegers/date#133]
Is this a bug in laravel-date or do i use it the wrong way?

![bildschirmfoto 2015-05-05 um 09 30 00](https://cloud.githubusercontent.com/assets/5419165/7468506/a49a4eda-f309-11e4-9720-3c485203414b.png)

**Comment by kjbstar** [comment]
Same here, with L4.2.
I rolled back to laravel-date 2.0.21 and all is fine now.

**Comment by jsphpl** [comment]
Great, many thanks @kjbstar!

**Comment by jsphpl** [comment]
Is >=3.0 only for L5?

**Comment by jenssegers** [comment]
No, it should work for both L4 and L5.

**Comment by jsphpl** [comment]
Can we help in debugging it?

**Comment by hotrush** [comment]
same error. rolling back to v2 helped

**Comment by AndreasHeiberg** [comment]
+1 on 4.2.17

**Comment by iivanov2** [comment]
The error message seems very clear:

Call to undefined method Symfony\Component\Translation\Translator::getMessages()

there is not getMessages() in Translator, the problem is that Laravel 4.2.17 can't install Carbon 1.18 because it requires sympfony/translation 2.6+  but Laravel 4.2 can update only to  sympfony/translation 2.5.11. I opened a related issue about Carbon here:
https://github.com/briannesbitt/Carbon/issues/365

Because laravel-date is extending Carbon, may be these two problems are related.

**Comment by jenssegers** [comment]
Why are you doing the `array_replace_recursive`? Isn't ` $all = static::getTranslator()->getCatalogue()->all();` enough?

**Comment by iivanov2** [comment]
Hi,
getCatalogue() is missing in Symfony\Component\Translation\Translator.php (version sympfony/translation 2.5.11). Notice that Laravel 4.2 can update sympfony/translation only to 2.5.*
see its composer file:
https://github.com/laravel/framework/blob/4.2/composer.json
I don't know how to update Laravel 4.2 to higher version of sympfony libraries and will that cause dependency problems. I think you have to write substitute of getMessages() and/or getCatalogue() in your Date class

**Comment by jenssegers** [comment]
For 4.2 I think it is best to use v2 instead of v3.

**Comment by iivanov2** [comment]
But it does not have all languages as v3.

**Comment by messi89** [comment]
same error 

rollback to to v2.*

**Comment by will-design78** [comment]
Someone has found a fix to this error? No dirty fix and rollback.
I'm working L4.2.
