### ISSUE TITLE
Bug with translation from ru to en

### ISSUE THREAD

**Issue by Elelas** [jenssegers/date#198]
Hi! Sorry, my english is bad =(

In

`Date::setLocale('ru');
$date = Date::translateTimeString('понедельник 21 март 2015');`

Out

`"monday 21 март 2015"`

my composer.json is
`"jenssegers/date": "^3.2"
"php": ">=5.5.9",
"laravel/framework": "5.1.*",`

Do i something wrong or is it really bug?

**Comment by limenet** [comment]
@Elelas my Russian is non-existent, so no problem there!

The way I see it (or rather, how someone who speaks some Russian just explained to me), Russian uses different cases for nouns, depending on how they're used. The same applies to months -- depending on context, "March" is written as "мартa" or "март". Correct?

Now, the way `translateTimeString()` works is by using basic array and string functions. And since "march" is translated as follows in the `ru.php` file, this simple approach doesn't work:

`'march' => '{0}март|{1}мартa',`

Not because of encoding issues, but because of how the algorithm is implemented.

This means, you didn't do anything wrong, @Elelas ! This is a bug.

---

Example: the following (for German) works correctly:
```
Date::setLocale('de');
$date = Date::translateTimeString('Montag 21 März 2015');
// "monday 21 march 2015"
```
