### ISSUE TITLE
Counting weeks - rounding down issue

### ISSUE THREAD

**Issue by UnrulyNatives** [jenssegers/date#214]
Hi, 
I guess the week counting needs some adjustments. 
I use your package to display time remaing to an event in a Laravel 5.2 app:

```
{{ $date = Jenssegers\Date\Date::parse($upcoming->date_start)->diffForHumans() }}
```
## Problem

if the remaining time is even 1 hour less than 2 weeks (14 days minus 1 hour) the displayed time is 1 week instead of two. 
The method rounds ALWAYS DOWN, while it should be rounding up along a customary method
for 1,5 ---> rounds up to 2
1.4 ---> rounds up to 1

Thank you. Outside the above glitch, your package is great!

Peter

**Comment by jenssegers** [comment]
Would like some more input on this though. I'm not 100% sure if rounding up is wanted in some cases.

**Comment by danhunsaker** [comment]
The generally expected behavior, in my experience with these kinds of things, is for these approximations to be as close to the actual value as practical, at the given resolution.  That does, indeed, mean rounding `x.0` through `x.4999...` to `x`, and `x.5` through `x.9999...` to `x+1` - the default behavior, I believe, of `round()`, and for that reason.

**Comment by jenssegers** [comment]
This behaviour is currently the same as in Carbon. So we probably don't want to change this. I changed the method's logic to be exactly the same as Carbon: 158f708

**Comment by mostafa6765** [comment]
```php
{{ Date::parse($upcoming->date_start)->ago() }}
```
you can try this @UnrulyNatives

**Comment by UnrulyNatives** [comment]
Great! I will check it today. Thank you very much!!

Peter
