### ISSUE TITLE
how parse format

### ISSUE THREAD

**Issue by ikakey** [jenssegers/date#216]
hi @carnevalle !

how parse this format:

today
tomorrow
yesterday 
next week
two week
next month

etc

**Comment by kylekatarnls** [comment]
For the record, this is available for intervals in Carbon:

```php
echo CarbonInterval::parseFromLocale('2 semaines', 'fr');
// You can use Carbon::getLocale() instead of 'fr' to use the global current locale
```

And soon it will be available for tomorrow/yesterday:
https://github.com/briannesbitt/Carbon/pull/2094

So Jenssegers\Date will have it by inheritance.

For words like "next", it's a bit different since it's not part of the actual translations, so it would need to be implemented for each language by a native speaker who can check it. So I don't think this part of the feature could be implemented (mostly not in every of the hundred of languages).
