### ISSUE TITLE
Key overlapping in russian locale

### ISSUE THREAD

**Issue by artygrand** [jenssegers/date#272]
https://github.com/jenssegers/date/blob/master/src/Lang/ru.php#L31
https://github.com/jenssegers/date/blob/master/src/Lang/ru.php#L44

Translation goes wrong

**Comment by mg-code** [comment]
Not only in Russian. In Latvian as well.

**Comment by danhunsaker** [comment]
This will apply to every locale, since the English name is identical in both short and full forms, and it is English names being used as keys (thanks in part to how PHP works). A proper mechanism to address this is going to require some thought and some adjustment to how the library functions, but is important for every language, not just Russian or Latvian.

**Comment by GinoPane** [comment]
@jenssegers Hi! Are you going to look into this?

**Comment by RosomahaG** [comment]
Here are several another languages that have same problem:
- de.php
- et.php
- fi.php
- lv.php
- nl.php
- ru.php
- uk.php
- uz.php

**Comment by MaxNozhkin** [comment]
+1

**Comment by jenssegers** [comment]
Yeah overlooked this issue. But not sure how to work around this.

**Comment by artygrand** [comment]
Maybe check what name is needed before use?
I made [this](https://github.com/sydes/framework/blob/master/src/L10n/Locales/RuLocale.php#L33) for myself

**Comment by kylekatarnls** [comment]
I suggest to add a dot to all short keys. Then replace `$translated = mb_substr($translated, 0, 3);` with `$translated = mb_substr($translated, 0, 3).'.';`
