### ISSUE TITLE
setLocale not working in Blade views

### ISSUE THREAD

**Issue by Jaspur** [jenssegers/date#276]
@jenssegers  how can I set the locale on the fly when using it in Views? 

Tried the following:
```
{{ Date::setLocale(auth()->user()->locale)->createFromTimeStamp(strtotime(auth()->user()->subscription))->format('j F Y') 
```
But didn't help, because some null-error issue. 

Regarding the docs you should do this in the Controller:
```
Date::setLocale(auth()->user()->locale);
```
That'll work, but only when you're using it inside the controller. Not when using it in a Blade-view..

Also tried making a Middleware where it set the Locale based on the authenticated users, but still not recognized in the blade view..

**Comment by MaxChu23** [comment]
You should create a middleware which will automatically detect the language from session variable and then set locale, because locale is not persistent in laravel. I did it as follows ( sorry for formatting :DD ):

1) In the `app\Providers\AppServiceProvider.php`:

`Date::setLocale(app()->getLocale());`

2) Then run `php artisan make:middleware Language` and edit `app\Http\Middleware\Language.php` like this:

` public function handle(){`
`if (Session::has('applocale') && array_key_exists(Session::get('applocale'), Config::get('languages'))) {
     App::setLocale(Session::get('applocale'));
 }`
` return $next($request);
}`

3) `Route::get('/setlocale/{locale}', function ($locale) {
  if (in_array($locale, array_keys(\Config::get('languages')))) {
    Session::put('applocale',$locale);
  }
  return redirect()->back();
});`

In later versions, I think it will be fixed by laravel developers.

**Comment by Jaspur** [comment]
Hi @MaxChu23 , thanks, but I tried almost the same thing. Still it's not working when using it in your blade views with the correct language.

```
# LanguageMiddleware
public function handle($request, Closure $next)
{
    if (auth()->check()) {
        
        app()->setLocale(auth()->user()->locale);
        Date::setLocale(auth()->user()->locale);
        Session::put('applocale', auth()->user()->locale);
        if (auth()->user()->locale != 'nl') {
            // This part works, the formatting
            config(['settings.date_format' => 'F j, Y']);
        }
        // some extra setting the locale
        if (Session::has('applocale')) {
            App::setLocale(Session::get('applocale'));
            Date::setLocale(Session::get('applocale'));
        }

    } 
    return $next($request);
}
```

It's returned correctly in the HTML when I added it:
```
<html lang="{{ config('app.locale') }}" locale="{{ session('applocale') }}" >
``

Result: 
```
<html lang="en" locale="en">
```

cc @jenssegers

**Comment by rodrigopedra** [comment]
@Jaspur 

The static `setLocale(...)` method does not return a new instance, so it is not chainable and you cannot use it like in your example

~~~php
{{ Date::setLocale(auth()->user()->locale)->createFromTimeStamp(strtotime(auth()->user()->subscription))->format('j F Y')
~~~

I tried to do this in a Blade view and it worked as expected:

~~~php
@php(\Jenssegers\Date\Date::setLocale('es'))

{{ \Jenssegers\Date\Date::createFromTimestamp(1519899120)->format('j F Y') }}
~~~

Please note I hardcoded the locale and the timestamp for simplicity.

Also setting the locale in the controller and using it in the view worked for me too.

**Comment by kylekatarnls** [comment]
@jenssegers The solution of @rodrigopedra is correct, I guess this could be closed.

Whit Carbon the following syntax is also available (and recommended as it does not change globally the locale):

```php
Date::createFromTimeStamp(strtotime(auth()->user()->subscription))->locale(auth()->user()->locale)->format('j F Y')
```

And my 2 cents, don't double-convert, you get data loss if there is a DST, simply do:
```php
Date::parse(auth()->user()->subscription)->locale(auth()->user()->locale)->format('j F Y')
```
