### ISSUE TITLE
Incompatible declaration of diffForHumans method

### ISSUE THREAD

**Issue by DojoGeekRA** [jenssegers/date#280]
When i ran `composer update` i found that with the release of [briannesbitt/carbon 1.23.0](https://github.com/briannesbitt/Carbon/releases/tag/1.23.0) the `diffForHumans` method declaration is incompatible with the current one:

```
ErrorException: Declaration of

Jenssegers\Date\Date::diffForHumans(
  ?Carbon\Carbon $since = NULL, $absolute = false, $short = false
)

should be compatible with

Carbon\Carbon::diffForHumans(
  ?Carbon\Carbon $other = NULL, $absolute = false, $short = false, $parts = 1
)
```

The related PR is https://github.com/briannesbitt/Carbon/pull/772

**Comment by DojoGeekRA** [comment]
Duplicate of https://github.com/jenssegers/date/issues/81

**Comment by ackerchez** [comment]
This is still happening today!

**Comment by mrvanwagoner** [comment]
Date::diffForHumans should be:

public function diffForHumans(Carbon $other = null, $absolute = false, $short = false, $parts = 1)

**Comment by leviatan21** [comment]
FYI: in my project, temporary switch to previous carbon version:
in the **composer.json** find: 
`"nesbot/carbon": "~1.0"`
replace with:
`"nesbot/carbon": "1.22.*"`

Hope this works for you too.

**Comment by ackerchez** [comment]
Seems the Carbon pull is coming from something else. I don't have that in my composer.json folder. I do have it in my composer.lock

**Comment by sebastiansulinski** [comment]
I came across this problem upgrading to `Laravel 5.6`, which makes use of `backpack/base`, which uses `jenssegers/date`.

**Comment by ackerchez** [comment]
If you just add "nesbot/carbon": "1.22.*" to composer.json it should override and work fine.

**Comment by kylekatarnls** [comment]
Hi, sorry guys but yes, now Carbon has a fourth optional argument that allow multiparts diffs. I recommend to inspect if Jessengers Date really still needs to override diffForHumans. It could maybe benefit of the new Carbon implemantation and mabye mutualize evolution efforts of this method in Carbon.

**Comment by BethanyMarriott** [comment]
Still an issue.

**Comment by Seaclick** [comment]
> If you just add "nesbot/carbon": "1.22.*" to composer.json it should override and work fine.

Not working for me, still an issue.

**Comment by kylekatarnls** [comment]
@Seaclick did you run `composer update` after that, because there is strictly no reason to get this error before carbon 1.23.

**Comment by Seaclick** [comment]
@kylekatarnls Thanks for your reply. Yep I did it, and got the same error on `composer update.`

**Comment by Seaclick** [comment]
@kylekatarnls I didn't have nesbot/carbon in my composer.json, I had to add it.

**Comment by kylekatarnls** [comment]
The following solution should works for everyone:

Run at the root of your project:
```shell
composer require nesbot/carbon=1.22.*
```

This is the best thing to do until Jenssegers/Date publish a version compatible, then you will be able to remove it from you composer.json and benefit of the new features of Carbon.

**Comment by Seaclick** [comment]
@kylekatarnls 
Thanks. Still have the same issue when trying to install nesbot/carbon with
`composer require nesbot/carbon:1.22`
=> Jenssengers/Date / Carbon/Carbon issue message

Should I try to uninstall Jenssegers/Date then install nesbot/carbon with a composer require?

**Comment by danhunsaker** [comment]
The problem is that Carbon keeps making BC-breaking API changes, and only bumping the minor version number. Date should, in turn, lock to minor versions rather than major ones, but doesn't currently do so (because SemVer suggests BC breaks bump the _major_ version instead, I would guess). A patch release of Date that adjusts the dependency appropriately would resolve this issue until 1.23 compatibility can be properly implemented. In the meantime, users need to introduce this limitation manually to their own projects instead.

**Comment by ametad** [comment]
Thanks @danhunsaker for the info.!

**Comment by jenssegers** [comment]
Try v3.3.0 of this package.

**Comment by rodrigopedra** [comment]
It is working, thanks! 

I've just pulled the repo to try to write a patch myself, glad I saw the release before digging into doing any work.

Tested with Portuguese, Spanish and German locales.

**Comment by inalto** [comment]
forcing a
`composer require jenssegers/date:3.3.1`
fixed my octobercms issue.

**Comment by kylekatarnls** [comment]
@danhunsaker Adding a optional argument is not a breaking change. If we forbid ourselves to make those improvements,  we will tag any change as major because if we say so, then adding a method is the same thing. If you used the same method name with other arguments count, it will break you app.

So I'm truly sorry but by extending Carbon, you enter the protected scope of Carbon, and semantic version only imply to keep backward compatibility for public scope. The same goes for us, when PHP add DateTime arguments, methods and so on from PHP 7.0 to 7.1 or to 7.2 (and it happened for several methods), it's fine to have a minor release version, we have to adapt Carbon, and publish a new version with the PHP compatibility.

The PR for the change was validated for more than one year. And the same way we test Carbon on PHP alpha/beta version, Jenssegers/Date can test and prepare Carbon changes using dev-master.

Jenssegers/Date updated very quickly and deleting the custom diffForHumans from it seems to me a very good option. And the same way we chose minor tag, Jenssegers use also a minor release which is perfectly relevant to me.

**Comment by Seaclick** [comment]
OK, so it's fixed for me...

This is what I've done :

Adding $parts = 1 to jenssegers/date::diffForHumans
`Jenssegers\Date\Date::diffForHumans(?Carbon\Carbon $since = NULL, $absolute = false, $short = false, **$parts = 1**)`
That's kill the error on composer update.

then run `composer update` which passed the package from 3.2.* to 3.3.1

**Comment by kylekatarnls** [comment]
@Seaclick please don't edit manually your vendor, it's the worst thing to do, just upgrade jenssegers or downgrade carbon is enough.

**Comment by Seaclick** [comment]
@kylekatarnls Thanks, but i've tried it... upgrade jensseggers or downgrade carbon always returned this error : 

[ErrorException]                                                                                                                                                                                                                                         
  Declaration of Jenssegers\Date\Date::diffForHumans(?Carbon\Carbon $since = NULL, $absolute = false, $short = false) should be compatible with Carbon\Carbon::diffForHumans(?Carbon\Carbon $other = NULL, $absolute = false, $short = false, $parts = 1)

**Comment by kylekatarnls** [comment]
It must be because you broke your vendor (maybe you have a non-interactive flag than prevent from erase packages you manually edited). So I recommend to remove vendor directory, remove nesbot/carbon from your composer.json then just run `composer update`.

**Comment by Seaclick** [comment]
mmm, i've never touch vendors before this problem... So this is not the reason of my issue...

**Comment by asbiin** [comment]
jenssegers/date 3.3.1 fixes this issue. Thanks !

**Comment by segsalerty2013** [comment]
Who else is *now* getting the following error:
```
Parse error: syntax error, unexpected '?', expecting variable (T_VARIABLE) {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Parse error: syntax error, unexpected '?', expecting variable (T_VARIABLE) at /Users/***/***/***/vendor/symfony/translation/Translator.php:79)
```

@asbiin - The issue on `composer update` gone but this wont allow app to run.

**Comment by kylekatarnls** [comment]
@segsalerty2013 it's not related to this issue and it sounds like a PHP version problem (upgrading to Symfony translation 4 with a too old PHP version).

**Comment by asbiin** [comment]
@segsalerty2013 yes you're right, I've got the error with php 7.0, but it's OK with php 7.1 or php 7.2.
This is due to symfony/translation:4.0 : https://github.com/symfony/translation/blob/master/Translator.php#L79

Try adding to your composer.json:
"symfony/translation": "3.4.*"

**Comment by segsalerty2013** [comment]
@asbiin Thanks, this fix the issue. 
My PHP version is `PHP 7.1.14 (cli) (built: Feb  2 2018 08:42:59) ( NTS )` though

**Comment by Seaclick** [comment]
@kylekatarnls thanks for the advise. You're right, i'll do it.

**Comment by danhunsaker** [comment]
@kylekatarnls You're right about the major/minor with _internal_ API changes, of course. There's still the issue of pinning to a major version in a library that extends another, though, which is really where this problem came to light so quickly and loudly for so many folks. Crisis averted for the moment, but i have to wonder about future changes of this nature, especially as this isn't the first or even second example of this happening with this particular project.

**Comment by kylekatarnls** [comment]
My recommendations to avoid such crises:

- By extending Carbon you enter the protected level and so you need to have automated builds that tests your library against dev-master version of Carbon, this way, you will now something change before the stable release and will be able to adapt softly, warn users, ask for Carbon project to take it into account. 
- By override a method you take a risk and must be aware of it. Before any override you should first consider other (often better) options:
  - Propose a PR to Carbon to allow you change in a way that does not need an override (setting, parameter, etc.)
  - Create an other method (so your users can use the native Carbon or yours and each method live its life)
  - If need some soft global override, intercept __call() that you're sure it will not have prototype change
- Check Carbon roadmap time to time (active PRs, future milestones) and check consequences. It's legit that it's the responsibility of library that extends an other, the same way Carbon watch DateTime coming changes.

**Comment by briannesbitt** [comment]
Glad you all got up and running again.  I see in the end the override of `diffForHumans()` was just simply removed.

**Comment by DojoGeekRA** [comment]
I can confirm that this issue is fixed in the [3.3.1](https://github.com/jenssegers/date/releases/tag/v3.3.1) release, thanks @jenssegers!

**Comment by NwosuCC** [comment]
This topic is marked as 'solved' and hence 'closed' but I hope someone can still give me some reply.
I think this is more of a 'Help' request than an 'Issue...'.

I have pulled in nesbot/carbon:1.23 and then jenssegers/date:3.3.1
```
composer require nesbot/carbon:1.23
composer require jenssegers/date:3.3.1
```
So, where in my project do I make lavavel (5.4) use 'jenssegers/date' instead of 'carbon\carbon', and when is this necessary (i guess not always?) ?

Searched in stackoverflow.com without success... still searching.
Anyone help, please

**Comment by Kreshnik** [comment]
This issue is still happening...

**Comment by kylekatarnls** [comment]
diffForHumans no longer exist in jessengers/date, it only happens if you use incompatible versions together.

jessenger >= 3.3.0 needs carbon >= 1.23.0
jessenger <3.3.0 needs carbon < 1.23.0

You cannot mix, it's as simple as that.

**Comment by martondob** [comment]
This combo did it for me:
`$ composer require jenssegers/date:^3.2`
`$ composer require nesbot/carbon:1.22.*`

Which ended up to be:
jenssegers/date (v3.4.0)
nesbot/carbon (1.22.1)

And it finally throws no error!
This oddly contradicts with @kylekatarnls https://github.com/jenssegers/date/issues/280#issuecomment-384216717

But it works for me : )
Maybe someone else will also benefit.

Thanks to:
* @DelightedD0D for https://github.com/jenssegers/date/issues/277#issuecomment-368266988
* @ackerchez  for https://github.com/jenssegers/date/issues/280#issuecomment-369347606
