### ISSUE TITLE
Support Carbon 2 ?!

### ISSUE THREAD

**Issue by oriceon** [jenssegers/date#310]
```php
In Date.php line 12:

  Declaration of Jenssegers\Date\Date::add($interval) must be compatible with Carbon\Carbon::add($unit, $value = 1, $overflow = NULL)
```

**Comment by kylekatarnls** [comment]
I proposed a collaboration for Carbon 2 - Jenssegers/Date a long time ago but still no news: #293

Jenssegers/Date tried to fulfill some missing features of Carbon 1 and we took some of them in Carbon 2.

For example, the method add() you mention has no longer any advantage on the Carbon 2 add method.

So it may be not relevant anymore to use Jenssegers/Date if you use Carbon 2. What do you need exactly from Jenssegers/Date?

**Comment by jenssegers** [comment]
Updating to Carbon 2 trips a lot of failing tests. I removed the custom `add` and `sub` methods, but for some reason all diffs are 1 day off:

```
Failed asserting that two strings are identical.
--- Expected
+++ Actual
@@ @@
-'5 days'
+'4 days'
```

Will look into why exactly this is happening.

**Comment by kylekatarnls** [comment]
Previously, the microseconds truncation would provide you a convenient (but wrong) rounding.

Example:
```php
$now = Carbon::now();
Carbon::now()->addDay()->diffInDays($now); // 1 day + few microseconds => 1 day
$now->addDay()->diffInDays(Carbon::now()); // 1 day - few microseconds => 0 days
```

And in fact previously, you did not get "1 day" every time, you only get 1 if `$now` and the `Carbon::now()` ran few time later did not overlap to an other second. For example in the previous version if you fall on the "unlucky" following case:


```php
$now1 = Carbon::now(); // 2000-01-01 00:00:00.990000
$now2 = Carbon::now(); // 2000-01-01 00:00:01.010000
$now1->addDay()->diffInDays($now2); // 0 days
```

So the day off  could also happen *randomly* with the previous version, this was definitely buggy and the new behavior now provide exact results. To align this in unit tests, you need to use a common now instance (or use setTestNow testing aid) so you won't have those few microseconds elapsed between 2 calls.

**Comment by rluders** [comment]
Any news about the Carbon 2 support? Is there someone working on it? Do you need help?

**Comment by kylekatarnls** [comment]
I added a lot of stuff for internationalization in Carbon 2 (next version will embed 823 locales languages/regions). This is now a big gap with jessengers (58). That means a simple support of Carbon 2 is no longer the relevant thing to do, because if made as is, you can loose some Carbon features and locales when using Jessengers.

IMO, Jessengers need a major update (some rethinking and refactor) and I understand @jenssegers may not be interested in such a work.

Still only my opinion, but here are some points that seem required to me:
- A new major release that require Carbon 2 and drop Carbon 1 (this also implicitly drop PHP < 7.1)
- Rely on Carbon 2 translations: remove the whole Lang directory. That will solve a lot of issues open for a long time (https://github.com/jenssegers/date/pulls)
- Remove methods that exist in Carbon, just alias them when names are different. For example the `format` override is equivalent to `isoFormat` of Carbon 2 (less the ~800 additional supported locales)
- Provide Jessengers as a Carbon mixin (that will allow to use it with other extensions), it can be for example a trait, that both the class and the mixin use, so you can have the same methods using either the class, the trait or the mixin.
- Check for all equivalent and re-center on what the Jessengers added value will be on the next version. As far as I known, format, diffForHumans, parse and timespan are now well ported in Carbon and so only left `createFromFormat`. If so, the library should maybe re-focus on the feature with a wider options set for it if relevant, else, it could be instead ported in Carbon. I would happily merge a PR for that.

If all features of Jessenders/date end in Carbon 2, maybe the Jessenders/date could rather become to provide some equivalent features that exist in Carbon 2 to Carbon 1. But I'm not sure it worth the effort.

**Comment by jenssegers** [comment]
Indeed, when switching to Carbon 2 there is much less relevance for this package. I do think the Carbon translation files are rather complicated, but that's something the end users never really need to work with.

One option would indeed be to release a new major release with support for Carbon 2 as a compatibility package.

Another one would be to add translation support on top of another library like Chronos. But not sure what the added value of that would be exactly.

Will give this another thought but will already start on support for Carbon 2 as that is the most logical next step.

**Comment by kylekatarnls** [comment]
Hi @jenssegers, great to see you motivated. I can give a try on using internale Carbon translation in `createFromFormat`. If implemented in Carbon, we would rename it as `createFromLocaleFormat` or `createFromIsoFormat` because I try to keep methods behavior of native PHP DateTime class.

Quick note to say, Carbon 2 provide both `Carbon` and `CarbonImmutable` that should be extended.

The first option you mention can be done as a quick fix. Some jenssegers/date 3.5.0 could add some minimal compatibility for Carbon 2 (just enough not to throw errors), so jenssegers/date would not prevent carbon upgrade. I can provide a PR for this one.

Then the 4.0.0 dropping Carbon 1 could come later when you decided goal and roadmap.

**Comment by kylekatarnls** [comment]
#316 will fix the method prototypes incompatibilities but keep the methods and all behavior as is, so it provides compatibility for both Carbon 1 and 2.
