### ISSUE TITLE
A small error in the Turkmen locale.

### ISSUE THREAD

**Issue by SuperManPHP** [jenssegers/date#318]
Hi guys. The turkmen locale have a small bug. The index **_ago_** do not translate. 
Return this:

- 1 sekunt ago

- 1 minut ago

- 1 sagat ago

- ....

Expected this:

- 1 sekunt ozal

- 1 minut ozal

- 1 sagat ozal

- ...

This bug have bulgarian (bg) locale too.

**Comment by SuperManPHP** [comment]
And turkmen domain is **_tm_**

**Comment by SuperManPHP** [comment]
Do not _**tk**_. This is Tokelau's domain

**Comment by kylekatarnls** [comment]
Hello,

Thanks for your help.

`tk` this is not the country code, but the language code, they are different, because 1 country can have multiple languages and 1 language can be used in multiple countries:
https://fr.wikipedia.org/wiki/Liste_des_codes_ISO_639-1

And full code is `tk_TM` (language_REGION)

Translations of it are there:
https://github.com/briannesbitt/Carbon/blob/master/src/Carbon/Lang/tk_TM.php

Please edit and fill the missing translations:
```php
// translate the English values to the right (keep :time, :count, {1}, ]1,Inf[ unchanged)
    'ago' => ':time ago',
    'from_now' => ':time from now',
    'after' => ':time after',
    'before' => ':time before',
    'diff_now' => 'just now',
    'diff_yesterday' => 'yesterday',
    'diff_tomorrow' => 'tomorrow',
    'diff_before_yesterday' => 'before yesterday',
    'diff_after_tomorrow' => 'after tomorrow',
    'period_recurrences' => '{1}once|{0}:count times|]1,Inf[:count times',
    'period_interval' => 'every :interval',
    'period_start_date' => 'from :date',
    'period_end_date' => 'to :date',
```

And add your name in the `Authors:` list to appear in our translators list: https://carbon.nesbot.com/contribute/translators/

You can do the whole thing on GitHub, it will ask you to fork, will automatically create a branch, then you'll be able to create a `Pull request` with this branch.

Thanks

**Comment by SuperManPHP** [comment]
Of course. Thanks!

**Comment by kylekatarnls** [comment]
Great, feel free to ask if you have any trouble in submitting the pull request.
