### ISSUE TITLE
Usage of deprecated Symfony methods to translate and format

### ISSUE THREAD

**Issue by xfudox** [jenssegers/date#327]
Just installed and tried the example, received this:

```
PHP Deprecated:  The "Symfony/Component/Translation/Translator::transChoice()" method is deprecated since Symfony 4.2, use the trans() one instead with a "%count%" parameter. in /var/www/html/vendor/symfony/translation/Translator.php on line 229
PHP Deprecated:  The "Symfony/Component/Translation/Formatter/MessageFormatter::choiceFormat()" method is deprecated since Symfony 4.2, use the format() one instead with a %count% parameter. in /var/www/html/vendor/symfony/translation/Formatter/MessageFormatter.php on line 69
```

Is there any plan to update/fix this?

**Comment by xfudox** [comment]
So this is it? No questions, no answer, just close my issue?

**Comment by jenssegers** [comment]
I don't think this is an issue anymore in the latest release. Have you updated already?

**Comment by kylekatarnls** [comment]
@xfudox those deprecations are handled. Carbon 2 supports:
```
"symfony/translation": "^3.4 || ^4.0 || ^5.0"
```
`%count%` is not supported in 3.4 so we're forced to use `transChoice()` for 3.x and which is the method cross-compatible among versions from 3 to 5. And since 4.2 `transChoice` is deprecated (you're using Symfony > 4.2 <5 I guess).

And in Symfony 5, it's removed and we use `->trans()` when `->transChoise()` is not available.

In Carbon 3, we won't support Symfony < 5 anymore.

As you can see the deprecation is perfectly handled. What you should do is migrate to Symfony 5. But if you don't want to. It's fine to stay on Symfony 4 and those deprecation actually are not a problem at all for you, because it's not up to you to handle them.

**Comment by kylekatarnls** [comment]
I insist about this point: deprecations are not errors you should handle in a fast or mandatory way. A deprecated method (if the library owner correctly used deprecation) is still supposed to works as before and as expected. It just tells you: it will no longer exist in the future (a precise version if specified, or else you can assume it disappear on the next major version). Then the deprecation often propose an alternative that would help you to migrate later in an easier way. So you can follow the deprecation advice to anticipate a possible future migration and so be ready already.

But you could still ignore every deprecation and handle them only when you actually upgrade. At this moment, then the doc, changelog or migration guide of the given library would tell you "foobar method is removed", which would no longer trigger a notice but a fatal error. Then it would still not be too late to replace the method according to the migration guide and you would be all fine.
