### ISSUE TITLE
defualt value to be null. 

### ISSUE THREAD

**Issue by desidude03** [jenssegers/date#332]
================sample code-Laravel=================================

public function createTableRow(Request $request)
     {
      $Date_of_Fault = Date::parse($request->data['Date_of_Fault'])->format('Y-m-d');
 $updatedRoles['data'] = DB::table('rma')
                        ->insert([
                           'Date_of_Fault' => $Date_of_Fault ,
  ]);
  }
=============================================================
 in frontend m using angular. but date works fine according to format specified. except when i send empty date value it takes "present date" in backend. i want it to be null as i specified in table and migrations

**Comment by kylekatarnls** [comment]
If `parse()` would return `null` (`Carbon::make()` does it if you wanna try) you would get an exception since you can't call `->format()` on `null`. So the cleanest way is:

```php
$Date_of_Fault = $request->data['Date_of_Fault']
  ? Date::parse($request->data['Date_of_Fault'])->format('Y-m-d')
  : null;
$updatedRoles['data'] = DB::table('rma')
->insert([
'Date_of_Fault' => $Date_of_Fault ,
]);
```

And there is not good reason IMHO for **jenssegers/date** to support creating instance from `null` value but return `null` when calling `format()` sounds not like a responsibility for the library.

Note than **jenssegers/date** does not override this behavior. It only replace the Carbon I18N feature by its own, all other features directly come from Carbon. See https://carbon.nesbot.com/docs/#api-instantiation
