### ISSUE TITLE
Date::parse('February')->month returns 3

### ISSUE THREAD

**Issue by waiylgeek** [jenssegers/date#337]
When using `Date::parse('February')->month` the returned result is 3. Same result is returned when using another language `Date::parse('Février')->month` always returns 3

But works as expected when running `Date::parse('1 February')->month` returns 2 which is correct.

Is this a bug or something else I ignore?

<img width="277" alt="Screen Shot 2020-03-30 at 11 05 35 PM" src="https://user-images.githubusercontent.com/4692358/77966859-d8dd2f80-72db-11ea-8da4-838a2703e29a.png">

**Comment by kylekatarnls** [comment]
The same happen with `new DateTime('February')` with pure PHP if you're a 30 or 31 day e.g. > 28 or 29 if leap year. Because PHP will create you a date from "now", let's say `2020-03-31 10:52:30 UTC` then it will change the month to February as asked by the string and so get: `2020-02-31 10:52:30 UTC` but as this date is not valid, it will overflow to the next month (2 days because 31 - number of days in February 2020) => `2020-03-02 10:52:30 UTC`

You rather should use the start of month with:
```php
Date::parse('February 1');
Date::parse('Février 1');
```

**Comment by waiylgeek** [comment]
> The same happens with `new DateTime('February')` with pure PHP if you're a 30 or 31 day e.g. > 28 or 29 if leap year. Because PHP will create you a date from "now", let's say `2020-03-31` then it will change the month to February as asked by the string and so get: `2020-02-31` but as this date is not valid, it will overflow to the next month (2 days because 31 - number of days in February 2020) => `2020-03-02`
> 
> You rather should use the start of month with:
> 
> ```
> Date::parse('February 1');
> Date::parse('Février 1');
> ```

This explains why when I run `Date::parse('1 February')->month` it works properly.

Thank you! — Gonna close the issue now.
